[test]
preload = ["./test-setup.ts"]
pathIgnorePatterns = ["^.*/packages/web/", "^.*/packages/lsp-tools-mcp/", "^.*/packages/lsp-daemon/", "^.*/packages/omop-codex/", "^.*/script/"]

[loader]
".md" = "text"
